version: "{build}"

branches:
  except:
    - /^travis.*$/

clone_depth: 10

os: Visual Studio 2015

platform: 
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - md build
  - cd build
  - if "%PLATFORM%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%PLATFORM%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" -T "v140_xp"
    -DCMAKE_BUILD_TYPE="%CONFIGURATION%"
    ..

build:
  project: build\GZDoom.sln
  parallel: true
  verbosity: minimal

after_build:
  - set OUTPUT_DIR=%APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\
  - 7z a ..\gzdoom.zip "%OUTPUT_DIR%gzdoom.exe" "%OUTPUT_DIR%*.pk3"

artifacts:
  - path: gzdoom.zip

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
