version: "{build}"

branches:
  except:
    - /^travis.*$/

clone_depth: 10

os: Visual Studio 2015

platform: 
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - md build
  - cd build
  - if "%PLATFORM%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%PLATFORM%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - set DEPS_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%\ci_deps_win\include
  - set DEPS_LIB_DIR=%APPVEYOR_BUILD_FOLDER%\ci_deps_win\lib\%PLATFORM%
  - cmake -G "%CMAKE_GENERATOR_NAME%" -T "v140_xp"
    -DCMAKE_BUILD_TYPE="%CONFIGURATION%"
    ..

build:
  project: build\GZDoom.sln
  parallel: true
  verbosity: minimal

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
