version: "{build}"

branches:
  except:
    - /^travis.*$/

clone_depth: 10

image:
  - Visual Studio 2019
  - Visual Studio 2015

environment:
  matrix:
    - ARCH: x64
    - ARCH: Win32

build_script:
  - md build
  - cd build
  - cmake -A %ARCH% -DPK3_QUIET_ZIPDIR=YES ..
  - cmake --build . --config Release -- -maxcpucount -verbosity:minimal

after_build:
  - set OUTPUT_DIR=%APPVEYOR_BUILD_FOLDER%\build\Release\
  - 7z a ..\LAD.zip "%OUTPUT_DIR%LAD.exe" "%OUTPUT_DIR%*.pk3"

artifacts:
  - path: LAD.zip

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
